version: '3.8'

networks:
 dev:
  name: dev

services:
 zookeeper:
  container_name: zookeeper_service
  image: confluentinc/cp-zookeeper:latest
  networks:
   - dev
  environment:
   ZOOKEEPER_CLIENT_PORT: 2181
   ZOOKEEPER_TICK_TIME: 2000
  ports:
   - 22181:2181

 kafka:
  container_name: kafka_service
  image: confluentinc/cp-kafka:latest
  depends_on:
   - zookeeper
  networks:
   - dev
  ports:
   - 29092:29092
  environment:
   KAFKA_BROKER_ID: 1
   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
   KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
   KAFKA_SOCKET_REQUEST_MAX_BYTES: 524288000
   KAFKA_MESSAGE_MAX_BYTES: 524288000
   KAFKA_CFG_MAX_REQUEST_SIZE: 524288000

 mongo:
    container_name: report_bd
    image: mongo
    restart: always
    networks:
     - dev
    ports:
     - 27017:27017
    environment:
     MONGO_INITDB_ROOT_USERNAME: rs
     MONGO_INITDB_ROOT_PASSWORD: 1

 app:
  container_name: report_service
  build:
   context: .
   dockerfile: Dockerfile
  networks:
    - dev
  depends_on:
   - mongo
